### ISSUE TITLE
Doing your mod anything related to fastutil?

### ISSUE THREAD

**Issue by TheButterbrotMan** [CammiePone/Icarus#16]
https://pastebin.com/GKVwdbwr

https://pastebin.com/ajKvGBWG

**Comment by CammiePone** [comment]
Icarus doesn't show up in either stacktrace. Why are you reporting it to me?

**Comment by TheButterbrotMan** [comment]
My users are telling me it happens when they fly with the wings.

**Comment by TheButterbrotMan** [comment]
So i dont know how you coded your mod, and dont know if fastutil is included. So i wanted to asked you, if it could be your mod.

**Comment by CammiePone** [comment]
FastUtil is included by Minecraft. Anything to do with flight itself is handled by Fabric API and Minecraft. I've been using my mod on a server a lot, flying literally everywhere instead of walking and have 0 problems.

Whatever the problem is, it has nothing to do with Icarus. Rule number 1 of making bug reports is find out if you can reproduce the bug in a vacuum. If you can, then it's on the mod alone. If you cant, then you need to find out what mod, or mods, is causing it to break in conjunction. If it's multiple, try and narrow it down to just two of them, rather than assume every mod running is partly responsible.
