### ISSUE TITLE
origin brokey :( for 1.20.0/.1

### ISSUE THREAD

**Issue by goobertizer** [CammiePone/Icarus#77]
the version of the mod for 1.20.0 and 1.20.1 seems to not have a working icarae origin, i dont even see it as an option in the origin menu or in the command line

**Comment by CammiePone** [comment]
yes, it was removed due to it being not worth the effort to keep it updated. between MC's major breaking changes, fixing existing bugs with the origin, and Origin's own breaking changes, it was just too much effort

as a result, it dragged the mod itself down in many ways that arent immediately obvious, like delaying updates to whenever Origins updated since i couldnt run my dev env without it being updated and Icarus having the new changes from Origins (which are usually undocumented and require a lot of headaches to fix)
